"""Constants."""
SENSOR_ROOM_FLOOR = 1
SENSOR_FLOOR = 3
SENSOR_ROOM = 4

REGULATION_SCHEDULE = 1
REGULATION_COMFORT = 2
REGULATION_MANUAL = 3
REGULATION_VACATION = 4
REGULATION_FROST_PROTECTION = 6
REGULATION_BOOST = 8
REGULATION_ECO = 9

DATETIME_FORMAT = "%Y-%m-%dT%H:%M:%S"
COMFORT_DURATION = 240
